import Head from "next/head";
import { Heading } from "@chakra-ui/react";
import { getJobList, getJobById } from "@/libs/api-recruitment";

export default function Home(props) {
  console.log({ job: props.job_details });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading>Front End Developer Test</Heading>
      </main>
    </>
  );
}

export async function getStaticProps(context) {
  const {
    params: { id_job },
  } = context;
  const job_details = await getJobById(id_job);
  return {
    props: {
      job_details,
    },
    revalidate: 10,
  };
}

export async function getStaticPaths() {
  const job_details = await getJobList();

  const paths = job_details.map((item) => ({
    params: { id_job: item.id },
  }));

  return { paths, fallback: "blocking" };
}
