import { useState } from "react";
import Head from "next/head";
import { Button, Heading } from "@chakra-ui/react";
import { getJobList } from "@/libs/api-recruitment";
import { useInfiniteQuery } from "@tanstack/react-query";

export default function Home(props) {
  const [page, setPage] = useState(1);
  const [description, setDescription] = useState("");
  const [location, setLocation] = useState("");
  const [fullTime, setFullTime] = useState(false);
  const {
    status,
    data,
    error,
    isFetching,
    isFetchingNextPage,
    isFetchingPreviousPage,
    fetchNextPage,
    fetchPreviousPage,
    hasNextPage,
    hasPreviousPage,
  } = useInfiniteQuery({
    queryKey: ["jobs"],
    queryFn: async ({ pageParam = 1 }) =>
      getJobList(pageParam, description, location, fullTime),
    initialData: props.jobs,
    getPreviousPageParam: () => 1,
    getNextPageParam: () => 2,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading>Front End Developer Test</Heading>
        <Button
          onClick={() => {
            setPage(page + 1);
            console.log({ page });
            fetchNextPage();
          }}
        >
          Next
        </Button>
        <Button onClick={() => fetchPreviousPage()}>Prev</Button>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const jobs = await getJobList(1);
  return {
    props: { jobs }, // will be passed to the page component as props
  };
}
